github: [ClusterM]
custom: ["https://www.patreon.com/c/ClusterMeerkat", "https://www.buymeacoffee.com/cluster", "https://messenger.online.sberbank.ru/sl/Lnb2OLE4JsyiEhQgC", "https://boosty.to/cluster"]
