"""
Copyright (C) 2025 Alexey Cluster <cluster@cluster.wtf>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

"""WireGuard configuration file generation"""

import logging
from typing import Dict, List

from ..config.constants import INTERNAL_WG_PORT

logger = logging.getLogger(__name__)


class WireGuardConfigGenerator:
    """Generates WireGuard configuration files"""
    
    @staticmethod
    def generate_server_config(
        config: Dict,
        clients: Dict,
        external_port: int,
        obfuscation: bool
    ) -> str:
        """
        Generate WireGuard server configuration file content
        
        Args:
            config: Main configuration dictionary
            clients: Clients configuration dictionary
            external_port: External port number
            obfuscation: Whether obfuscation is enabled
            
        Returns:
            Configuration file content as string
        """
        lines = []
        lines.append("# Generated by wg-obf-easy-api")
        lines.append("[Interface]")
        lines.append("FwMark = 0xdead")  # Add patch line
        lines.append(f"PrivateKey = {config['server_private_key']}")
        
        if not obfuscation:
            lines.append(f"ListenPort = {external_port}")
        else:
            lines.append(f"ListenPort = {INTERNAL_WG_PORT}")
        
        lines.append(f"Address = {config['subnet']}.{config['own_ip']}/24")
        lines.append(
            f"PostUp = iptables -A FORWARD -i {config['wg_interface']} -j ACCEPT; "
            f"iptables -A FORWARD -o {config['wg_interface']} -j ACCEPT; "
            f"iptables -t nat -A POSTROUTING -o {config['wan_interface']} -j MASQUERADE; " # Edit patch line
            f"iptables -t mangle -A PREROUTING -i {config['wan_interface']} "  # Add patch line
            f"-p tcp --dport 5000 -j CONNMARK --set-mark 0xdead; "  # Add patch line
            f"iptables -t mangle -A OUTPUT -p tcp --sport 5000 "  # Add patch line
            f"-m connmark ! --mark 0 -j CONNMARK --restore-mark"  # Add patch line
        )
        lines.append(
            f"PostDown = iptables -D FORWARD -i {config['wg_interface']} -j ACCEPT; "
            f"iptables -D FORWARD -o {config['wg_interface']} -j ACCEPT; "
            f"iptables -t nat -D POSTROUTING -o {config['wan_interface']} -j MASQUERADE; " # Edit patch line
            f"iptables -t mangle -D PREROUTING -i {config['wan_interface']} "  # Add patch line
            f"-p tcp --dport 5000 -j CONNMARK --set-mark 0xdead; "  # Add patch line
            f"iptables -t mangle -D OUTPUT -p tcp --sport 5000 "  # Add patch line
            f"-m connmark ! --mark 0 -j CONNMARK --restore-mark"  # Add patch line
        )
        
        for client_name, client in clients.items():
            # Skip disabled clients
            if not client.get('enabled', True):
                continue
            lines.append("")
            lines.append("[Peer]")
            # Names stored by older versions may contain line breaks, which would
            # let the comment escape into a forged config section
            lines.append("# " + " ".join(str(client_name).split()))
            lines.append(f"PublicKey = {client['public_key']}")
            if client.get('preshared_key'):
                lines.append(f"PresharedKey = {client['preshared_key']}")
            #lines.append(f"AllowedIPs = {config['subnet']}.{client['ip']}/32")  # Del patch line
            if client_name == "EXT_Server":  # Add patch line
                lines.append("AllowedIPs = 0.0.0.0/0") # Add patch line
            else: # Add patch line
                lines.append(f"AllowedIPs = {config['subnet']}.{client['ip']}/32") # Add patch line
            lines.append("PersistentKeepalive = 25")
        
        lines.append("")
        config_content = "\n".join(lines)
        logger.debug(f"Generated WireGuard server config ({len(lines)} lines)")
        return config_content
    
    @staticmethod
    def generate_client_config(
        config: Dict,
        client: Dict,
        external_ip: str,
        external_port: int,
        obfuscation: bool,
        allowed_ips: List[str],
        default_obfuscator_port: int = 13255
    ) -> str:
        """
        Generate WireGuard client configuration file content
        
        Args:
            config: Main configuration dictionary
            client: Client configuration dictionary
            external_ip: External IP address
            external_port: External port number
            obfuscation: Whether obfuscation is enabled
            allowed_ips: List of allowed IP ranges
            default_obfuscator_port: Default obfuscator port for client
            
        Returns:
            Configuration file content as string
        """
        lines = []
        lines.append("[Interface]")
        lines.append(f"PrivateKey = {client['private_key']}")
        lines.append(f"Address = {config['subnet']}.{client['ip']}/32")
        lines.append("")
        lines.append("[Peer]")
        lines.append(f"PublicKey = {config['server_public_key']}")
        if client.get('preshared_key'):
            lines.append(f"PresharedKey = {client['preshared_key']}")
        lines.append(f"AllowedIPs = {', '.join(allowed_ips)}")
        
        if obfuscation:
            lines.append(f"Endpoint = 127.0.0.1:{client.get('obfuscator_port', default_obfuscator_port)}")
        else:
            lines.append(f"Endpoint = {external_ip}:{external_port}")
        
        lines.append("PersistentKeepalive = 25")
        lines.append("")
        
        config_content = "\n".join(lines)
        logger.debug(f"Generated WireGuard client config for client {client.get('ip', 'unknown')}")
        return config_content
    
    @staticmethod
    def save_config_file(config_content: str, wg_interface: str) -> None:
        """
        Save WireGuard configuration to file
        
        Args:
            config_content: Configuration file content
            wg_interface: WireGuard interface name
        """
        config_path = f"/etc/wireguard/{wg_interface}.conf"
        with open(config_path, "w") as f:
            f.write(config_content)
        logger.debug(f"Saved WireGuard config to {config_path}")

