"""
Copyright (C) 2025 Alexey Cluster <cluster@cluster.wtf>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

"""Obfuscator configuration file generation"""

import logging
from typing import Dict, Optional

from ..config.constants import WG_OBFUSCATOR_CONFIG_FILE, DEFAULT_CLIENT_OBFUSCATOR_PORT

logger = logging.getLogger(__name__)


class ObfuscatorConfigGenerator:
    """Generates wg-obfuscator configuration files"""
    
    @staticmethod
    def generate_server_config(
        external_port: int,
        obfuscation_key: str,
        masking_type: str,
        masking_forced: bool,
        verbosity_level: str,
        allow_clean: bool = False
    ) -> str:
        """
        Generate obfuscator server configuration file content
        
        Args:
            external_port: External port number
            obfuscation_key: Obfuscation key
            masking_type: Masking type (NONE, STUN, etc.)
            masking_forced: Whether masking type is forced for all clients
            verbosity_level: Verbosity level (ERROR, WARNING, INFO, DEBUG, TRACE)
            allow_clean: Whether to accept non-obfuscated WireGuard clients
            
        Returns:
            Configuration file content as string
        """
        from ..config.constants import INTERNAL_WG_PORT
        
        lines = []
        lines.append("# Generated by wg-obf-easy-api")
        lines.append("[main]")
        lines.append(f"source-lport = {external_port}")
        lines.append(f"target = 127.0.0.1:{INTERNAL_WG_PORT}")
        lines.append(f"key = {obfuscation_key}")
        
        if allow_clean:
            lines.append("allow-clean = true")
        
        if masking_forced:
            lines.append(f"masking = {masking_type}")
        else:
            lines.append("masking = AUTO")
        
        lines.append(f"verbose = {verbosity_level}")
        lines.append(f"fwmark = 0xdead")  # Add patch line
        lines.append("")
        
        config_content = "\n".join(lines)
        logger.debug("Generated obfuscator server config")
        return config_content
    
    @staticmethod
    def generate_client_config(
        client: Dict,
        external_ip: str,
        external_port: int,
        obfuscation_key: str,
        masking_type: str,
        masking_forced: bool,
        verbosity_level: str = "INFO"
    ) -> str:
        """
        Generate obfuscator client configuration file content
        
        Args:
            client: Client configuration dictionary
            external_ip: External IP address
            external_port: External port number
            obfuscation_key: Obfuscation key
            masking_type: Default masking type
            masking_forced: Whether masking type is forced
            verbosity_level: Verbosity level
            
        Returns:
            Configuration file content as string
        """
        lines = []
        lines.append("[main]")
        lines.append(f"source-lport = {client.get('obfuscator_port', DEFAULT_CLIENT_OBFUSCATOR_PORT)}")
        lines.append(f"target = {external_ip}:{external_port}")
        lines.append(f"key = {obfuscation_key}")
        
        # Masking type per client
        if masking_forced:
            # Only one masking type for all clients
            lines.append(f"masking = {masking_type}")
        else:
            # Masking type per client
            masking = client.get('masking_type_override', None)
            if masking is None:
                masking = masking_type
            lines.append(f"masking = {masking}")
        
        lines.append(f"verbose = {client.get('verbosity_level', verbosity_level)}")
        lines.append("")
        
        config_content = "\n".join(lines)
        logger.debug(f"Generated obfuscator client config")
        return config_content
    
    @staticmethod
    def save_config_file(config_content: str) -> None:
        """
        Save obfuscator configuration to file
        
        Args:
            config_content: Configuration file content
        """
        with open(WG_OBFUSCATOR_CONFIG_FILE, "w") as f:
            f.write(config_content)
        logger.debug(f"Saved obfuscator config to {WG_OBFUSCATOR_CONFIG_FILE}")

